# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=45)),
                ('model', models.CharField(max_length=45)),
                ('year', models.IntegerField(max_length=4)),
                ('condition', models.CharField(max_length=45)),
                ('body_style', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
                ('mileage', models.IntegerField(max_length=45)),
                ('price', models.IntegerField(max_length=45)),
                ('color', models.CharField(max_length=45)),
                ('transmission', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
