# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-29 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_auto_20180627_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='body_style',
        ),
        migrations.RemoveField(
            model_name='car',
            name='color',
        ),
        migrations.RemoveField(
            model_name='car',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='car',
            name='location',
        ),
        migrations.RemoveField(
            model_name='car',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='car',
            name='transmission',
        ),
        migrations.AddField(
            model_name='car',
            name='desc',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='video',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
