# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-29 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='Cars.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_cars', to='Cars.User'),
        ),
    ]
